add_newline = true

format = """
$character $git_metrics $git_state $git_status
$username $directory $git_branch $cmd_duration\
$python\
$c\
$php\
$nodejs\
$cmake\
$java\
$haskell
 [{}](bold white) """

right_format = "$git_commit $time"


[username]
show_always = true
style_root = "fg: green"
style_user = "fg:#f9f1a5 bg:#212227"
format = "[](fg:#212227)[$user]($style)[](fg:#212227)"


[cmd_duration]
min_time = 1000

[character]
success_symbol = " 🔥 "
error_symbol = "[-👎](bold red)"

[directory]
style = "fg:#EFC88B"
format = "[ $path]($style)"
repo_root_format = "[ $repo_root]($repo_root_style)[$path]($style)"
repo_root_style = "fg:#5EFC8D"
truncation_length = 3 
truncate_to_repo = true
truncation_symbol = "…"


[git_commit]
format = "[DETACHED head](bold red): [$hash]($style)"

[git_status]
# conflicted = "⚔️ "
# ahead = "⇡${count}"
# behind = "⇣${count}"
# diverged = "🔱(⇡${ahead_count} ⇣${behind_count})"
# untracked = "_×${count}"
# stashed = "📦"
# modified = "📝${count} "
# staged = "🗃️×${count} "
# renamed = "凜 ×${count}"
# deleted = "🗑️×${count}"
# style = "bright-white"
format = "$all_status$ahead_behind"

[time]
disabled = false
time_format = "%H:%M"

[nodejs]
symbol = " "

[package]
symbol = " "


[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "
