# [default]
# extend-ignore-identifiers-re = [
#     # *sigh* this just isn't worth the cost of fixing
#     "AttributeID.*Supress.*",
# ]

[default.extend-identifiers]
# *sigh* this just isn't worth the cost of fixing

[default.extend-words]
# Nvim plugin name
noice = "noice"

# part of a regex
upport = "upport"

# program
ags = "ags"

[files]
extend-exclude = [
  "CHANGELOG.md"
]
