add_newline = true

format=""" $character $git_metrics $git_state $git_status ${custom.git-town} $nix_shell ${custom.fsh}
$username $directory $git_branch $cmd_duration\
$docker_context\
$azure\
$aws\
$python\
$c\
$php\
$nodejs\
$cmake\
$java\
$haskell
 [{}](bold white) """

right_format = """${status}
$git_commit $time"""



[custom.fsh]
description = "Indicates when I'm in FHS env."
symbol = '\(FHS\)'
when = 'test -n "$FHS"'
style = "blink dimmed blue"

[character]
success_symbol = " 🔥 "
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 1000

[directory]
style = "fg:#EFC88B"
format = "[ $path]($style)"
repo_root_format = "[ $repo_root]($repo_root_style)[$path]($style)"
repo_root_style = "fg:#5EFC8D"
truncation_length = 3 
truncate_to_repo = true
truncation_symbol = "…"
read_only = " 󰌾"

[git_commit]
format = "[DETACHED head](bold red): [$hash]($style)"

[time]
disabled = false
time_format = "%H:%M"
format = '| [$time]($style)'

[nix_shell]
# format = '[$state($symbol \($name\))]($style)'
# format = "[\ue0c7](#ffedbd)[ $state($symbol \\($name\\))](bg:#ffedbd fg:blue)[\ue0c6](#ffedbd)"
format = '[$state($symbol \($name\))]($style)'
impure_msg=""
symbol = ""
heuristic = true

# -------------------

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "


[nodejs]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[azure]
disabled = false
format = 'on [$symbol($subscription)]($style) '
symbol = '󰠅 '
style = 'blue bold'

[custom.git-town]
command = "git town status --pending"
when = ""
require_repo = true

[status]
disabled =  false
format = '[ $status \[$symbol$signal_name$signal_number $common_meaning$maybe_int\]]($style) '
# format = '[ $status $pipestatus \[$symbol$signal_name$signal_number $common_meaning$maybe_int\]]($style) '
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
pipestatus = true