{ pkgs, ... } : {
	services.openssh = {
		enable = true;
  	
		# require public key authentication for better security
  	settings.PasswordAuthentication = false;
  	settings.KbdInteractiveAuthentication = false;
	};

	users.users = {
		leswell.openssh.authorizedKeys.keys = [
			"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM0SGvG+JRSZRPtCOU3y2SOSqH/3uyIVt6AZ9iIciZuM leswell@leswell-nixos"
		];

		root.openssh.authorizedKeys.keys = [
			"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM0SGvG+JRSZRPtCOU3y2SOSqH/3uyIVt6AZ9iIciZuM leswell@leswell-nixos"
			"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGrgjalwu78SAUYR7wJPWCDc4ws/zqyUY3MDZMu6sEnM Generated By Termius"
		];
	};
}
