name: "Test"
on:
  pull_request:
  push: 
    branches:
      - main
      - man-of-culture
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v15
      with:
        name: charm-os
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - run: nix flake check
    - run: nix build .#nixosConfigurations.leswell-nixos.config.system.build.toplevel 
    - run: nix build .#nixosConfigurations.leswellhp.config.system.build.toplevel 
